version: '2'
services:
  flask:
    build: ./flask  
    container_name: flask-api
    # restart: always
    expose:
    - 8000
  nginx:
    build: ./nginx
    container_name: nginx_flask
    ports:
      - 8000:80
    depends_on:
      - flask
