name: Flask CICD

# 觸發條件
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# 執行一項或多項任務
jobs: 
  CD:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    # 遠端部署
    - name: route
      run:
        cd ~/code
    - name: clone
      run:
        git clone https://github.com/w110056005/docker-sample.git
    - name: route
      run:
        cd ./docker-sample
    - name: docker build & compose
      run:
        docker image build -t sample-flask-api . \
        docker-compose up -d
    - name: route
      run:
        cd .. 
    - name: remove folder
      run:
        rm -rf flask-api
    
