name: Flask CICD

# 觸發條件
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# 執行一項或多項任務
jobs: 
  CD:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    # 遠端部署
    - name: CD
      run:
        cd ~/code,
        mkdir flask-api,
        cd ./flask-api,
        git clone https://github.com/w110056005/docker-sample.git,
        docker-compose up --build -d,
        cd ..,
        rm -rf flask-api
    
