name: Flask CICD

# 觸發條件
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# 執行一項或多項任務
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    # 遠端部署
    - name: CD to Target folder
      run:
        cd ~/code/docker-sample
    - name: Pull source
      run:
        git pull https://github.com/w110056005/docker-sample.git
    - name: CD
      run:
        docker-compose up --build -d
